[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars-catalog"
repository = "https://github.com/gauteh/dars"
license = "MIT"
description = "Catalog for dars-dap"
version = "0.1.0"

[dependencies]
warp = "0.2"
hyper = "0.13"
tera = "1"
anyhow = "1"
lazy_static = "1"
rust-embed = "5"

[dependencies.serde]
features = ["derive"]
version = "1"

[dev-dependencies]
futures = "0.3"

