[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
description = "A fast and light OPeNDAP-subset server"
repository = "https://github.com/gauteh/dars"
license = "MIT"

[dependencies]
anyhow = "1"
async-stream = "0.2"
async-trait = "0.1"
colored = "1.9"
env_logger = "0.7"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
getopts = "*"
itertools = "0.8"
lazy_static = "1.4"
log = "0.4"
netcdf = "0.3"
netcdf-sys = "0.2"
notify = "4.0"
percent-encoding = "2.1"
roxmltree = "0.7"
walkdir = "2.2"

[dependencies.hyper]
features = ["stream"]
version = "0.13"

[dependencies.tokio]
features = ["full"]
version = "0.2"

[dependencies.tokio-util]
features = ["codec"]
version = "0.2"

[dependencies.xdr-codec]
features = ["bytecodec"]
version = "0.4"

