[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
[dependencies]
anyhow = "1.0.22"
env_logger = "0.7.1"
futures = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
itertools = "*"
lazy_static = "*"
log = "0.4.8"
netcdf = "0.3.1"
tokio = "0.2.0-alpha.6"

[dependencies.hyper]
features = ["unstable-stream"]
version = "0.13.0-alpha.4"
