[package]
name = "dredds"
version = "0.1.0"
authors = ["Gaute Hope <gaute.hope@met.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
tide = "0.3.0"
http = "0.1.19"
