[package]
name = "dredds"
version = "0.1.0"
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
netcdf = "0.3.1"
anyhow = "1.0.22"
futures = "0.3.1"
hyper = { version = "0.13.0-alpha.4", features = ['unstable-stream'] }
tokio = "0.2.0-alpha.6"
