[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
[dependencies]
anyhow = "1.0.22"
async-trait = "*"
env_logger = "0.7.1"
futures = "0.3.1"
futures-core = "0.3.1"
futures-util = "0.3.1"
itertools = "*"
lazy_static = "*"
log = "0.4.8"
netcdf = "0.3.1"
tokio = "0.2.0-alpha.6"

[dependencies.hyper]
features = ["unstable-stream"]
git = "https://github.com/hyperium/hyper"
