[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
[dependencies]
anyhow = "*"
colored = "*"
env_logger = "*"
futures = "*"
log = "*"
num_cpus = "*"
smol = "*"
tide = "*"
