[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
[dependencies]
anyhow = "*"
async-stream = "*"
bytes = "*"
colored = "*"
env_logger = "*"
flexbuffers = "*"
futures = "*"
getopts = "*"
hyper = "*"
itertools = "*"
jemallocator = "*"
lazy_static = "*"
libc = "*"
log = "*"
ndarray = "*"
num_cpus = "*"
roxmltree = "*"
sled = "0.34"
tokio-util = "*"
toml = "*"
walkdir = "*"
warp = "*"
bincode = "*"

[dependencies.dap2]
path = "../dap2"
version = "*"

# hdf5 repository is patched at workspace level
[dependencies.hdf5]
version = "^0.7.0"

[dependencies.hdf5-sys]
version = "^0.7.0"
features = ["static", "zlib"]

[dependencies.hidefix]
version = "*"
git = "https://github.com/gauteh/hidefix"

[dependencies.tokio]
features = ["full"]
version = "*"

[dependencies.serde]
features = ["derive"]
version = "*"

[features]
default = ["static"]
static = ["hdf5-sys/static", "hdf5-sys/zlib"]
