[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
[dependencies]
anyhow = "*"
async-trait = "*"
colored = "*"
env_logger = "*"
futures = "*"
itertools = "*"
libc = "*"
log = "*"
num_cpus = "*"
sled = "*"
tide = "*"
zerocopy = "*"

[dependencies.async-std]
features = ["attributes"]
version = "*"

[dependencies.dap2]
path = "../dap2"
version = "*"

[dependencies.hdf5]
branch = "hidefix"
git = "https://github.com/gauteh/hdf5-rust"

[dependencies.hdf5-sys]
branch = "hidefix"
features = ["static", "zlib"]
git = "https://github.com/gauteh/hdf5-rust"

[dependencies.hidefix]
git = "https://github.com/gauteh/hidefix"
version = "*"
