[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
repository = "https://github.com/gauteh/dars"
license = "MIT"
description = "𓃢   A fast and light OPeNDAP server"

[[bin]]
name = "dars"
path = "src/main.rs"

[dependencies]
anyhow = "*"
async-stream = "*"
async-trait = "*"
bincode = "*"
bytes = "*"
colored = "*"
env_logger = "*"
flexbuffers = "*"
futures = "*"
getopts = "*"
hyper = "*"
itertools = "*"
jemallocator = "*"
lazy_static = "*"
libc = "*"
log = "*"
ndarray = "*"
num_cpus = "*"
roxmltree = "*"
sled = "0.34"
tokio-util = "*"
toml = "*"
walkdir = "*"
warp = "*"

[dependencies.dap2]
path = "../dap2"
version = "*"

[dependencies.dars-catalog]
path = "../dars-catalog"
version = "*"
optional = true

[dependencies.hdf5]
version = "*"

[dependencies.hdf5-sys]
features = ["static", "zlib"]
version = "*"

[dependencies.hidefix]
features = ["static"]
git = "https://github.com/gauteh/hidefix"
version = "*"

[dependencies.serde]
features = ["derive"]
version = "*"

[dependencies.tokio]
features = ["full"]
version = "*"

[lib]
name = "dars"
path = "src/lib.rs"

[features]
default = ["catalog", "fast-index"]
catalog = ["dars-catalog"]
fast-index = ["hidefix/fast-index"]

