[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
name = "dars"
version = "0.1.0"
[dependencies]
anyhow = "*"
colored = "*"
env_logger = "*"
futures = "*"
itertools = "*"
log = "*"
num_cpus = "*"
sled = "*"
smol = "*"
tide = "*"
zerocopy = "*"

[dependencies.async-std]
features = ["attributes"]
version = "*"


[dependencies.hidefix]
version = "*"
git = "https://github.com/gauteh/hidefix"
